### ISSUE TITLE
Dataset splits

### ISSUE THREAD

**Issue by johntzwei** [jamesqo/wmt19-metrics-submission#1]
We need to make train/test/validation splits. The file `data/trg-en/set` contains the label of which year the test instance came from. I think RUSE was trained on 2015-2016 data and validated on 2017 data.

**Comment by johntzwei** [comment]
> Training. We divided the dataset for training and development at a 9:1 ratio. First, for testing in WMT16, we divided the segment-level dataset of WMT15 into 1800 instances for training and 200 instances for development. Next, for testing in WMT17, we divided the segment-level datasets of WMT15 and WMT16 into 4824 instances for training and 536 instances for development. Finally, for submission to WMT18, we divided the segment-level dataset of WMT15, WMT16, and WMT17 into 8352 instances for training and 928 instances for development.

For reference.

**Comment by jamesqo** [comment]
Do we have to reproduce which instances they trained/validated on? Since the data from WMT15/16/17 is all combined, we would have to separate them out again in order to implement that.

**Comment by johntzwei** [comment]
We would have to separate them out. The `data/trg-en/set` file contains line by line which WMT year they are from. We should implement two kinds of splitting, one like RUSE, and the other where we train on WMT15 + WMT16 and test on WMT17.

**Comment by johntzwei** [comment]
Added stratified k fold cross validation and filter by source.
