### ISSUE TITLE
Use ELMo word embeddings

### ISSUE THREAD

**Issue by johntzwei** [jamesqo/wmt19-metrics-submission#2]
Currently the performance is really bad, and training does not improve the Pearson correlation by much. There are a few reasons why this might be. One of the reasons is that 9280 examples is not enough to learn good word embeddings. We should try to get ELMo working and see if that improves the performance.

**Comment by jamesqo** [comment]
I found a tutorial on using ELMo w/ allennlp at https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md, so I'll try and see if I can get that working today.

**Comment by johntzwei** [comment]
I'm also pretty sure that our current implementation doesn't replace rare words with <unk>. Make sure that if you implement ELMo we can easily roll it back or switch back to the old one.
